// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MainUI_h
#define MainUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include "Workspace.h"
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Choice.H>

class MainUI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *window;
  static Fl_Menu_Item menu_[];
  static Fl_Menu_Item *menu_file_new;
  static Fl_Menu_Item *menu_file_open;
  static Fl_Menu_Item *menu_file_save;
  static Fl_Menu_Item *menu_file_saveas;
  static Fl_Menu_Item *menu_file_exit;
  Workspace *workspace;
  Fl_Scrollbar *scr_v;
  Fl_Scrollbar *scr_h;
  Fl_Button *tool6;
  Fl_Button *tool3;
  Fl_Button *tool0;
  Fl_Button *tool7;
  Fl_Button *tool4;
  Fl_Button *tool1;
  Fl_Button *tool8;
  Fl_Button *tool5;
  Fl_Button *tool2;
  Fl_Button *ink6;
  Fl_Button *ink3;
  Fl_Button *ink0;
  Fl_Button *ink7;
  Fl_Button *ink4;
  Fl_Button *ink1;
  Fl_Button *ink8;
  Fl_Button *ink5;
  Fl_Button *ink2;
  Fl_Box *fav_colors;
  Fl_Box *cur_color;
  Fl_Choice *layers;
  Fl_Button *layer_more;
  Fl_Button *layer_add;
  Fl_Button *layer_del;
};
#endif
